/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orai0408;

import java.awt.Color;
import java.util.Random;

/**
 *
 * @author Drégely Imre
 */
public class NewJFrame extends javax.swing.JFrame {

    private float eltalaltSzazalek;
    private int joValaszokSzama = 0;
    
    private float eredmeny;
    private int probalkozasokSzama;
    private int kerdesekSzama = 1;
    public NewJFrame() {
        initComponents();
        probalkozasokSzama = 0;
        lbKerdesekSzama.setText("Kérdések száma: " + kerdesekSzama);
        eredmeny = 10/5;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEredmeny = new javax.swing.JTextField();
        lbMuvelet = new javax.swing.JLabel();
        btnEllenoriz = new javax.swing.JButton();
        btnUjMuvelet = new javax.swing.JButton();
        pnVisszajelzes = new javax.swing.JPanel();
        btnMegoldas = new javax.swing.JButton();
        txtBontas = new javax.swing.JTextField();
        lbBontasLabel = new javax.swing.JLabel();
        pnStatisztika = new javax.swing.JPanel();
        lbKerdesekSzama = new javax.swing.JLabel();
        lbProbalkozasokSzama = new javax.swing.JLabel();
        lbSzazalek = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alapműveletek gyakorlása");

        lbMuvelet.setText("10/5 =");

        btnEllenoriz.setText("Ellenőriz");
        btnEllenoriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEllenorizActionPerformed(evt);
            }
        });

        btnUjMuvelet.setText("Új kifejezés kérése");
        btnUjMuvelet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUjMuveletActionPerformed(evt);
            }
        });

        pnVisszajelzes.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnVisszajelzesLayout = new javax.swing.GroupLayout(pnVisszajelzes);
        pnVisszajelzes.setLayout(pnVisszajelzesLayout);
        pnVisszajelzesLayout.setHorizontalGroup(
            pnVisszajelzesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );
        pnVisszajelzesLayout.setVerticalGroup(
            pnVisszajelzesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        btnMegoldas.setText("Megoldás");
        btnMegoldas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegoldasActionPerformed(evt);
            }
        });

        lbBontasLabel.setText("Alapműveletekre bontás");

        pnStatisztika.setName(""); // NOI18N

        lbKerdesekSzama.setText("Kérdések száma: ");

        lbProbalkozasokSzama.setText("Próbálkozások száma:");

        lbSzazalek.setText("Eredmény:");

        javax.swing.GroupLayout pnStatisztikaLayout = new javax.swing.GroupLayout(pnStatisztika);
        pnStatisztika.setLayout(pnStatisztikaLayout);
        pnStatisztikaLayout.setHorizontalGroup(
            pnStatisztikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnStatisztikaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnStatisztikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSzazalek)
                    .addComponent(lbProbalkozasokSzama)
                    .addComponent(lbKerdesekSzama))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        pnStatisztikaLayout.setVerticalGroup(
            pnStatisztikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnStatisztikaLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(lbKerdesekSzama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbProbalkozasokSzama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSzazalek)
                .addGap(24, 24, 24))
        );

        jMenu1.setLabel("Műveletek");

        jMenuItem1.setLabel("Osztás");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setLabel("Szorzás");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setLabel("Összeadás");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setLabel("Kivonás");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBontas)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnStatisztika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(83, 83, 83))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEllenoriz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUjMuvelet))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbMuvelet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEredmeny, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnVisszajelzes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbBontasLabel)
                            .addComponent(btnMegoldas))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbMuvelet)
                        .addComponent(txtEredmeny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnVisszajelzes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEllenoriz)
                    .addComponent(btnUjMuvelet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnStatisztika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMegoldas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(lbBontasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBontas, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEllenorizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEllenorizActionPerformed
        
        if (Float.parseFloat(txtEredmeny.getText()) == eredmeny) {
            pnVisszajelzes.setBackground(Color.GREEN);
            probalkozasokSzama++;
            lbProbalkozasokSzama.setText("Próbálkozások száma: " + probalkozasokSzama);
            joValaszokSzama++;
            eltalaltSzazalek = ((float)joValaszokSzama/probalkozasokSzama)*100;
            lbSzazalek.setText("Eredmény: " + Math.round(eltalaltSzazalek));
            btnEllenoriz.setEnabled(false);
            btnMegoldas.setEnabled(false);
        }else {
            pnVisszajelzes.setBackground(Color.RED);
            probalkozasokSzama++;
            lbProbalkozasokSzama.setText("Próbálkozások száma: " + probalkozasokSzama);
            eltalaltSzazalek = ((float)joValaszokSzama/probalkozasokSzama)*100;
            lbSzazalek.setText("Eredmény: " + Math.round(eltalaltSzazalek));
        }
    }//GEN-LAST:event_btnEllenorizActionPerformed

    private void btnMegoldasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegoldasActionPerformed
        txtEredmeny.setText(String.valueOf(eredmeny));
        btnEllenoriz.setEnabled(false);
        txtEredmeny.setEnabled(false);
        pnVisszajelzes.setBackground(Color.GRAY);
        kerdesekSzama++;
        lbKerdesekSzama.setText("Kérdések száma: " + kerdesekSzama);
    }//GEN-LAST:event_btnMegoldasActionPerformed

    private void btnUjMuveletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUjMuveletActionPerformed
        btnMegoldas.setEnabled(true);
        
        Random rnd = new Random();
        pnVisszajelzes.setBackground(Color.GRAY);
        
        int a = rnd.nextInt(100-1);
        int b = rnd.nextInt(100-1);
        
        eredmeny = (float)a/b;
        System.out.println(eredmeny);
        while(eredmeny > 100 && eredmeny % 1 == 0.5) {
           a = rnd.nextInt(100-1);
           b = rnd.nextInt(100-1);
           eredmeny = (float)a/b;
        }
        
        lbMuvelet.setText(a + "/" + b + "=");
        
        btnEllenoriz.setEnabled(true);
        txtEredmeny.setEnabled(true);
        
        
        
    }//GEN-LAST:event_btnUjMuveletActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEllenoriz;
    private javax.swing.JButton btnMegoldas;
    private javax.swing.JButton btnUjMuvelet;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JLabel lbBontasLabel;
    private javax.swing.JLabel lbKerdesekSzama;
    private javax.swing.JLabel lbMuvelet;
    private javax.swing.JLabel lbProbalkozasokSzama;
    private javax.swing.JLabel lbSzazalek;
    private javax.swing.JPanel pnStatisztika;
    private javax.swing.JPanel pnVisszajelzes;
    private javax.swing.JTextField txtBontas;
    private javax.swing.JTextField txtEredmeny;
    // End of variables declaration//GEN-END:variables
}
